---
title: "--- Day 14: Docking Data ---"
author: Fleur Kelpin
date: Dec 14, 2020
output: github_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
input <- tibble(line = readLines("day14.txt")) %>%
  extract(line, "mask", "mask = ([01X]{36})", remove = FALSE) %>%
  extract(line, c("address", "value"), "mem\\[(\\d+)\\] = (\\d+)", convert = TRUE)
input
```
# Part 1

Execute the initialization program. What is the sum of all values left in memory
after it completes?

```{r}
i2b <- function(value) {
  result <- logical(36)
  index <- 36
  while (value > 0) {
    result[index] <- value %% 2 == 1
    value <- value %/% 2
    index <- index - 1
  }
  result
}

b2d <- function(bits) {
  result <- 0
  for (index in 1:36) {
    if (bits[[index]]) {
      result <- result + 2**(36 - index)
    }
  }
  result
}

apply_mask <- function(value, mask) {
  bits <- i2b(value)
  mask <- unlist(str_split(mask, ""))
  masked_bits <-
    map_lgl(1:36, function(index) {
      switch(mask[index],
        "1" = TRUE,
        "0" = FALSE,
        "X" = bits[index]
      )
    })
  b2d(masked_bits)
}
```
```{r}
mem <- double()

for (i in 1:nrow(input)) {
  if (!is.na(input$mask[[i]])) {
    mask <- input$mask[[i]]
  } else {
    mem[input$address[[i]]] <- apply_mask(input$value[[i]], mask)
  }
}

options(digits = 22)
sum(mem, na.rm = TRUE)
```
