---
title: "--- Day 19: Monster Messages ---"
author: Fleur Kelpin
date: Dec 19, 2020
output: github_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
input <- tibble(line = readLines("day19-rules.txt")) %>%
  extract(line, c("number", "rules"), "(\\d+): (.*)") %>%
  extract(rules, "letters", "\"(\\w)\"", remove = F) %>%
  extract(rules, c("alt1", NA, "alt2"), "([0-9 ]*)(\\|(.*))?") %>%
  mutate(number = as.integer(number)) %>%
  extract(alt1, c("alt1a", "alt1b"), "([0-9]+)( [0-9]+)?", convert = T) %>%
  extract(alt2, c("alt2a", "alt2b"), "([0-9]+)( [0-9]+)?", convert = T) %>%
  arrange(number)
input

messages <- tibble(message = readLines("day19-messages.txt"))
messages
```
# Part 1
```{r}
getRegex <- function(num) {
  if (is.na(num)) {
    return("")
  }
  data <- input %>%
    filter(number == num)
  if (!is.na(data$letters[[1]])) {
    return(data$letters[[1]])
  }
  if (!is.na(data$alt2a[[1]])) {
    paste0(
      "(",
      getRegex(data$alt1a[[1]]),
      getRegex(data$alt1b[[1]]),
      "|",
      getRegex(data$alt2a[[1]]),
      getRegex(data$alt2b[[1]]),
      ")"
    )
  } else {
    paste0(
      "(",
      getRegex(data$alt1a[[1]]),
      getRegex(data$alt1b[[1]]),
      ")"
    )
  }
}
getRegex(0)
```

```{r}
messages %>%
  rowwise() %>%
  filter(str_detect(message, paste0("^", getRegex(0), "$"))) %>%
  nrow()
```
# Part 2
```{r}
getRegex2 <- function(num) {
  if (is.na(num)) {
    return("")
  }
  if (num == 8) {
    return(paste0("(", getRegex2(42), "+)"))
  }
  if (num == 11) {
    return(
      paste0(
        "(",
        getRegex2(42),
        "){5}(",
        getRegex2(31),
        "){5}"
      )
    )
  }
  data <- input %>%
    filter(number == num)
  if (!is.na(data$letters[[1]])) {
    return(data$letters[[1]])
  }
  if (!is.na(data$alt2a[[1]])) {
    paste0(
      "((",
      getRegex2(data$alt1a[[1]]),
      getRegex2(data$alt1b[[1]]),
      ")|(",
      getRegex2(data$alt2a[[1]]),
      getRegex2(data$alt2b[[1]]),
      "))"
    )
  } else {
    paste0(
      "(",
      getRegex2(data$alt1a[[1]]),
      getRegex2(data$alt1b[[1]]),
      ")"
    )
  }
}
regex <- paste0("^", getRegex2(0), "$")
regex
```
```{r}
messages %>%
  rowwise() %>%
  filter(str_detect(message, regex)) %>%
  nrow()
```

```{r}
363 + 35 + 13 + 3
```

